words = [
    {"Latin": "agitō -āre", "English": "drive"},
    {"Latin": "amō -āre", "English": "to love; lover"},
    {"Latin": "appellō -āre", "English": "call, address, name"},
    {"Latin": "celebrō -āre", "English": "frequent, throng, crowd"},
    {"Latin": "certō -āre", "English": "decide by contest; fight, compete, vie"},
    {"Latin": "cōgitō -āre", "English": "think, reflect"},
    {"Latin": "comparō -āre", "English": "get ready, provide; compare"},
    {"Latin": "cōnstō -āre -stitī", "English": "agree; constat, it is established that (+ acc. and infin.)"},
    {"Latin": "creō -āre", "English": "produce, create; elect, choose"},
    {"Latin": "cūrō -āre", "English": "watch over, look after, care for (+ acc.)"},
    {"Latin": "damnō -āre", "English": "condemn"},
    {"Latin": "dēsīderō -āre", "English": "long for, desire greatly"},
    {"Latin": "dō -are", "English": "give"},
    {"Latin": "dōnō -āre", "English": "present with a gift (+ acc. of person and abl. of thing)"},
    {"Latin": "dubitō -āre", "English": "hesitate, doubt"},
    {"Latin": "errō -āre", "English": "go astray, wander"},
    {"Latin": "exīstimō -āre", "English": "think, believe"},
    {"Latin": "exspectō -āre", "English": "watch, wait, expect"},
    {"Latin": "fugō -āre", "English": "put to flight"},
    {"Latin": "imperō -āre", "English": "command, control"},
    {"Latin": "indicō -āre", "English": "point out, show, make known"},
    {"Latin": "interrogō -āre", "English": "put a question to, ask (+ acc.)"},
    {"Latin": "intrō -āre", "English": "enter"},
    {"Latin": "iūdicō -āre", "English": "judge, decide"},
    {"Latin": "iūrō -āre", "English": "take an oath, swear; oath"},
    {"Latin": "iuvō -āre", "English": "help, assist; please, delight"},
    {"Latin": "labōrō -āre", "English": "toil, work; be in trouble or distress"},
    {"Latin": "laudō -āre", "English": "praise"},
    {"Latin": "mūtō -āre", "English": "change"},
    {"Latin": "narrō -āre", "English": "relate, recount"},
    {"Latin": "negō -āre", "English": "deny, refuse"},
    {"Latin": "occupō -āre", "English": "seize, occupy; anticipate, do a thing first (+ infin.)"},
    {"Latin": "optō -āre", "English": "choose, select"},
    {"Latin": "ōrō -āre", "English": "pray"},
    {"Latin": "parō -āre", "English": "prepare, acquire"},
    {"Latin": "peccō -āre", "English": "commit a wrong, injure"},
    {"Latin": "portō -āre", "English": "carry a load"},
    {"Latin": "praestō -āre", "English": "excel, exhibit"},
    {"Latin": "probō -āre", "English": "approve, prove; convince one (dat.) of a thing (acc.)"},
    {"Latin": "properō -āre", "English": "hasten, speed"},
    {"Latin": "pugnō -āre", "English": "fight"},
    {"Latin": "putō -āre", "English": "think, suppose"},
    {"Latin": "revocō -āre", "English": "call back, recall"},
    {"Latin": "rogō -āre", "English": "ask"},
    {"Latin": "servō -āre", "English": "save, watch over"},
    {"Latin": "sonō -āre", "English": "sound, resound"},
    {"Latin": "spectō -āre", "English": "look at, consider"},
    {"Latin": "spērō -āre", "English": "to hope"},
    {"Latin": "stō -āre", "English": "stand"},
    {"Latin": "superō -āre", "English": "overcome, surpass, defeat"},
    {"Latin": "temptō -āre", "English": "try, test"},
    {"Latin": "turbō -āre", "English": "disturb, confuse"},
    {"Latin": "vacō -āre", "English": "be empty, open, unoccupied"},
    {"Latin": "vetō -āre vetuī vetītum", "English": "forbid"},
    {"Latin": "vītō -āre", "English": "avoid, shun"},
    {"Latin": "vocō -āre", "English": "call"}
]
